### ISSUE TITLE
Common ways to define some complex drones

### ISSUE THREAD

**Issue by DamienCassou** [emacscollective/emacs.g#7]
Some drones require non-standard configuration in '.gitmodules'. Would it make sense to make borg write the following (or something equivalent) in '.gitmodules' for these packages automatically when `M-x borg-assimilate` is ran?

```gitconfig
[submodule "notmuch"]
	path = lib/notmuch
	url = git://notmuchmail.org/git/notmuch
	load-path = emacs
	info-path = doc/_build/texinfo
	build-step = ./configure
	build-step = make
	build-step = make sphinx-texinfo
	build-step = "(borg-makeinfo \"notmuch\")"
[submodule "org"]
	path = lib/org
	url = git://orgmode.org/org-mode.git
	load-path = lisp
	info-path = doc
	build-step = make compile autoloads info ORG_ADD_CONTRIB="ox-*"
```

If you don't want borg to do that automatically, what about adding a Wiki somewhere so that everyone can document?

**Comment by DamienCassou** [comment]
This is related to part of the discussion in https://github.com/emacscollective/borg/issues/10

**Comment by tarsius** [comment]
That's one way of doing it. My plan was to use "drone branches" and I have create a few such branches now. I'll open a `borg` issue and/or update the documentation at a later time to discuss the various possible approaches and how to use drone branches for the time being.

Just so much for now. I created such a branch for `org`. Please create one for `notmuch` by branching of `master` and then open a pr against that. Instead of actually merging, I will push your drone branch.
